version: '3'
services:
  mysql:
    image: postgres
    container_name: postgresTextEditor
    ports:
      - "8888:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_PASSWORD: 1111